insert into public.spots (
  id,
  city_code,
  category,
  name,
  name_ko,
  name_ja,
  name_en,
  name_ko_auto,
  name_ko_status,
  search_keywords,
  wikidata_id,
  source_name,
  source_url,
  source_license,
  rating,
  menu,
  tips,
  address,
  open_time,
  close_time,
  latitude,
  longitude,
  google_place_id,
  google_maps_url,
  sort_order
)
values
  ('sapporo-001', 'sapporo', 'spot', '오도리 공원 (Odori Park)', '오도리 공원 (Odori Park)', null, null, null, 'reviewed', '{"오도리 공원 (Odori Park)","공원 산책 및 구운 옥수수 맛보기 🌽","Odori Park, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.5', '공원 산책 및 구운 옥수수 맛보기 🌽', '삿포로 TV타워를 배경으로 완벽한 인생샷을 남길 수 있는 최고 명소입니다! 공원 내 포장마차(토키비 웨건)에서 파는 노릇노릇한 구운 옥수수와 버터 감자는 삿포로 여름의 상징이니 벤치에 앉아 꼭 드셔보세요.', 'Odori Park, Sapporo', '00:00', '24:00', null, null, null, null, 10),
  ('sapporo-002', 'sapporo', 'spot', '모이와야마 전망대 (Mt. Moiwa Ropeway)', '모이와야마 전망대 (Mt. Moiwa Ropeway)', null, null, null, 'reviewed', '{"모이와야마 전망대 (Mt. Moiwa Ropeway)","일본 3대 야경 로프웨이 탑승 🚡","Mt. Moiwa Ropeway, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.7', '일본 3대 야경 로프웨이 탑승 🚡', '해발 531m 정상에서 감상하는 삿포로 시내의 360도 은하수 야경은 압도적입니다. 산 정상의 ''사랑의 종''에서 하트 자물쇠를 걸거나 종을 함께 울리며 황홀하고 로맨틱한 삿포로의 밤을 연출해보세요.', 'Mt. Moiwa Ropeway, Sapporo', '10:30', '22:00', null, null, null, null, 20),
  ('sapporo-003', 'sapporo', 'noodle', '스프카레 스아게플러스 (Suage+)', '스프카레 스아게플러스 (Suage+)', null, null, null, 'reviewed', '{"스프카레 스아게플러스 (Suage+)","닭꼬치(시레토코도리) 스프카레 (약 1,400엔)","Suage+, South 4 West 5, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.5', '닭꼬치(시레토코도리) 스프카레 (약 1,400엔)', '가라쿠(GARAKU)의 줄이 너무 길어 포기해야 할 때 1티어 대안지! 숯불에 구운 닭고기가 꼬치에 꽂혀 나와 먹기 편하고 국물이 대단히 깊고 얼큰합니다. 가라쿠 바로 근처에 본점과 2호점이 붙어있어 웨이팅 분산이 빠릅니다.', 'Suage+, South 4 West 5, Sapporo', '11:30', '21:30', null, null, null, null, 30),
  ('sapporo-004', 'sapporo', 'noodle', '스프카레 트레져 (TREASURE)', '스프카레 트레져 (TREASURE)', null, null, null, 'reviewed', '{"스프카레 트레져 (TREASURE)","함바그 스프카레 (약 1,350엔)","스프카레 TREASURE, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.4', '함바그 스프카레 (약 1,350엔)', '스프카레 맛집 가라쿠(GARAKU)의 자매 브랜드 식당입니다. 비법 베이스 스프와 맛이 매우 유사하여 가라쿠 웨이팅이 감당이 안 될 때 바로 갈 수 있는 훌륭한 대안입니다. 철판 함바그 토핑이 대단히 잘 어울립니다.', '스프카레 TREASURE, Sapporo', '11:30', '20:30', null, null, null, null, 40),
  ('sapporo-005', 'sapporo', 'meat', '징기스칸 아루코 (Alco)', '징기스칸 아루코 (Alco)', null, null, null, 'reviewed', '{"징기스칸 아루코 (Alco)","생양고기 어깨살 & 양갈비 (약 1,200엔)","Arco Jingisukan, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.6', '생양고기 어깨살 & 양갈비 (약 1,200엔)', '다루마 본점과 스스키노 골목의 다른 지점에 줄이 수십 미터 서 있을 때 갈 수 있는 숨겨진 골목 생양고기 최강 대안! 고기 질이 다루마만큼 훌륭하고 가격도 착합니다. 아늑한 다찌석 위주로 조용히 맥주와 곁들이기 좋습니다.', 'Arco Jingisukan, Sapporo', '17:00', '22:00', null, null, null, null, 50),
  ('sapporo-006', 'sapporo', 'noodle', '라멘 요시야마 쇼텐 (Yoshiyama Shouten)', '라멘 요시야마 쇼텐 (Yoshiyama Shouten)', null, null, null, 'reviewed', '{"라멘 요시야마 쇼텐 (Yoshiyama Shouten)","매운 참깨 미소 라멘 (약 950엔)","Yoshiyama Shouten, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.3', '매운 참깨 미소 라멘 (약 950엔)', '라멘 신겐의 1~2시간 이상 웨이팅이 부담스러우시다면 삿포로역 ESTA 공화국이나 스스키노 빌딩 지하의 요시야마 쇼텐으로 가세요! 볶은 참깨의 고소함 and 삿포로 정통 미소의 감칠맛이 폭발하는 국물이 웨이팅 타협 이상의 맛을 선사합니다.', 'Yoshiyama Shouten, Sapporo', '11:00', '21:00', null, null, null, null, 60),
  ('sapporo-007', 'sapporo', 'seafood', '스시잔마이 스스키노점 (Sushizanmai)', '스시잔마이 스스키노점 (Sushizanmai)', null, null, null, 'reviewed', '{"스시잔마이 스스키노점 (Sushizanmai)","참치 세트 & 단품 초밥 (세트 약 2,500엔)","Sushizanmai Susukino, Sapporo"}'::text[], null, 'sapo-curated', null, null, '4.1', '참치 세트 & 단품 초밥 (세트 약 2,500엔)', '삿포로 유명 스시야들이 대부분 사전 예약제이거나 대기가 일찍 마감됩니다. 스시잔마이는 24시간 영업하여 늦은 밤 야식으로도 웨이팅 없이 신선한 홋카이도 해산물 스시를 맛볼 수 있는 최고의 전천후 대체지입니다.', 'Sushizanmai Susukino, Sapporo', '00:00', '24:00', null, null, null, null, 70),
  ('otaru-001', 'otaru', 'spot', '오타루 운하 (Otaru Canal)', '오타루 운하 (Otaru Canal)', null, null, null, 'reviewed', '{"오타루 운하 (Otaru Canal)","운하 가스등 산책 및 크루즈 탑승 🛥️","Otaru Canal, Otaru"}'::text[], null, 'sapo-curated', null, null, '4.6', '운하 가스등 산책 및 크루즈 탑승 🛥️', '일몰 30분 전부터 붉은 노을과 함께 가스등 노란 불빛이 운하를 따라 켜지는 순간이 가장 환상적으로 아름답습니다. 낮보다 밤이 훨씬 아름다운 스팟으로, 옛 벽돌 창고를 개조한 비어홀이나 카페도 함께 둘러보세요.', 'Otaru Canal, Otaru', '00:00', '24:00', null, null, null, null, 10),
  ('otaru-002', 'otaru', 'spot', '오타루 오르골당 (Otaru Music Box Museum)', '오타루 오르골당 (Otaru Music Box Museum)', null, null, null, 'reviewed', '{"오타루 오르골당 (Otaru Music Box Museum)","천상의 오르골 선율 감상 🎶","Otaru Music Box Museum"}'::text[], null, 'sapo-curated', null, null, '4.6', '천상의 오르골 선율 감상 🎶', '약 3만여 점에 달하는 아기자기한 오르골이 빛나는 세계 최대 규모의 오르골 전시장입니다. 입구의 상징적인 스팀 증기시계는 15분마다 아름다운 멜로디를 연주하며 증기를 뿜어내니 타이밍에 맞춰 인증샷을 찰칵!', 'Otaru Music Box Museum', '09:00', '18:00', null, null, null, null, 20),
  ('otaru-003', 'otaru', 'seafood', '오타루 도야마 (Otaru Toyama)', '오타루 도야마 (Otaru Toyama)', null, null, null, 'reviewed', '{"오타루 도야마 (Otaru Toyama)","도야마 특선 카이센동 (약 3,500엔)","Otaru Toyama Kaisendon"}'::text[], null, 'sapo-curated', null, null, '4.5', '도야마 특선 카이센동 (약 3,500엔)', '오타루역 삼각시장 내부의 타키나미 식당 웨이팅이 시장 밖까지 가득 차 있을 때 탈출할 수 있는 최고의 1선 대체지입니다! 삼각시장 바로 뒤쪽에 위치하며, 재료 신선도와 우니, 게살 토핑 양이 전혀 밀리지 않는 숨은 로컬 강자입니다.', 'Otaru Toyama Kaisendon', '11:00', '18:00', null, null, null, null, 30),
  ('otaru-004', 'otaru', 'seafood', '오타루 마사즈시 운하점 (Masazushi)', '오타루 마사즈시 운하점 (Masazushi)', null, null, null, 'reviewed', '{"오타루 마사즈시 운하점 (Masazushi)","타쿠미 스시 코스 (약 6,500엔)","Otaru Masazushi Zenan"}'::text[], null, 'sapo-curated', null, null, '4.4', '타쿠미 스시 코스 (약 6,500엔)', '미스터 초밥왕의 고향 오타루에서 가장 전통 있고 상징적인 대표 스시야입니다. 본관 웨이팅이 길다면 운하점의 아름다운 운하 전망 창가 자리를 노려보는 것을 적극 추천합니다. 이세즈시 대비 예약 난이도가 낮고 캐주얼합니다.', 'Otaru Masazushi Zenan', '11:00', '21:00', null, null, null, null, 40),
  ('otaru-005', 'otaru', 'dessert', '롯카테이 오타루점 (Rokkatei)', '롯카테이 오타루점 (Rokkatei)', null, null, null, 'reviewed', '{"롯카테이 오타루점 (Rokkatei)","슈크림 빵 & 유키콘치즈 (약 150엔~300엔)","Rokkatei Otaru"}'::text[], null, 'sapo-curated', null, null, '4.4', '슈크림 빵 & 유키콘치즈 (약 150엔~300엔)', '사카이마치 거리의 르타오(LeTAO) 카페 테이블 웨이팅 대기가 50팀이 넘어갈 때, 바로 옆에 있는 롯카테이 2층 카페 스탠딩석으로 가세요! 갓 구운 바삭한 슈크림 빵을 사면 무료로 원두커피 한 잔을 제공하는 혜택이 있어 가성비 쉼터로 제격입니다.', 'Rokkatei Otaru', '09:00', '18:00', null, null, null, null, 50),
  ('otaru-006', 'otaru', 'dessert', '기타카로 오타루 본점 (Kitakaro)', '기타카로 오타루 본점 (Kitakaro)', null, null, null, 'reviewed', '{"기타카로 오타루 본점 (Kitakaro)","홋카이도 우유 소프트 아이스크림 (약 400엔)","Kitakaro Otaru"}'::text[], null, 'sapo-curated', null, null, '4.3', '홋카이도 우유 소프트 아이스크림 (약 400엔)', '르타오 본점 웨이팅 타협을 위한 두 번째 대안! 기타카로 본관 안쪽의 조용하고 고풍스러운 정원에서 아주 진한 정통 홋카이도 목장 우유 맛 아이스크림과 달콤한 바움쿠헨 한 조각을 시켜서 벤치에 앉아 여유롭게 쉴 수 있습니다.', 'Kitakaro Otaru', '09:00', '18:00', null, null, null, null, 60),
  ('tokyo-001', 'tokyo', 'spot', '도쿄 타워 (Tokyo Tower)', '도쿄 타워 (Tokyo Tower)', null, null, null, 'reviewed', '{"도쿄 타워 (Tokyo Tower)","도쿄의 상징 전망대 관람 🗼","Tokyo Tower, Tokyo"}'::text[], null, 'sapo-curated', null, null, '4.7', '도쿄의 상징 전망대 관람 🗼', '도쿄의 오랜 랜드마크입니다. 시바 공원에서 도쿄 타워를 배경으로 돗자리를 펴고 피크닉 사진을 찍으면 인생샷을 쉽게 남길 수 있습니다.', 'Tokyo Tower, Tokyo', '09:00', '23:00', null, null, null, null, 10),
  ('tokyo-002', 'tokyo', 'spot', '아사쿠사 센소지 (Senso-ji)', '아사쿠사 센소지 (Senso-ji)', null, null, null, 'reviewed', '{"아사쿠사 센소지 (Senso-ji)","전통 사찰 산책 & 나카미세도리 길거리 간식","Sensoji Temple, Tokyo"}'::text[], null, 'sapo-curated', null, null, '4.6', '전통 사찰 산책 & 나카미세도리 길거리 간식', '도쿄에서 가장 오래된 절입니다. 입구의 붉은 거대 등(카미나리몬) 아래서 인증샷을 찍고 사찰 앞 상점가에서 화과자와 모찌를 즐겨보세요.', 'Sensoji Temple, Tokyo', '06:00', '17:00', null, null, null, null, 20),
  ('tokyo-003', 'tokyo', 'spot', '시부야 스카이 (Shibuya Sky)', '시부야 스카이 (Shibuya Sky)', null, null, null, 'reviewed', '{"시부야 스카이 (Shibuya Sky)","전망대 옥상 시부야 스크램블 뷰","Shibuya Sky, Tokyo"}'::text[], null, 'sapo-curated', null, null, '4.8', '전망대 옥상 시부야 스크램블 뷰', '시부야 스크램블 스퀘어 빌딩 옥상에 있는 전망대입니다. 일몰 시간대 예약이 가장 인기가 많으며, 바람을 맞으며 360도로 펼쳐진 야경은 장관입니다.', 'Shibuya Sky, Tokyo', '10:00', '22:30', null, null, null, null, 30),
  ('tokyo-004', 'tokyo', 'noodle', '이치란 라멘 신주쿠점', '이치란 라멘 신주쿠점', null, null, null, 'reviewed', '{"이치란 라멘 신주쿠점","천연 돈코츠 라멘 (약 980엔)","Ichiran Shinjuku, Tokyo"}'::text[], null, 'sapo-curated', null, null, '4.3', '천연 돈코츠 라멘 (약 980엔)', '한국인 입맛에 가장 잘 맞는 1인 독서실 형태의 유명 돈코츠 라멘집입니다. 매운맛 소스 레벨을 4~5단계 정도로 올리면 느끼함 없이 맛있게 드실 수 있습니다.', 'Ichiran Shinjuku, Tokyo', '10:00', '23:00', null, null, null, null, 40),
  ('osaka-001', 'osaka', 'spot', '도톤보리 (Dotonbori)', '도톤보리 (Dotonbori)', null, null, null, 'reviewed', '{"도톤보리 (Dotonbori)","글리코상 인증샷 & 타코야키 투어 🐙","Dotonbori, Osaka"}'::text[], null, 'sapo-curated', null, null, '4.6', '글리코상 인증샷 & 타코야키 투어 🐙', '오사카의 심장 같은 중심가입니다. 거대하고 화려한 입체 간판들을 배경으로 야경을 즐기고, 다리 밑 노점에서 파는 따끈한 타코야키를 맥주와 함께 즐겨보세요.', 'Dotonbori, Osaka', '00:00', '24:00', null, null, null, null, 10),
  ('osaka-002', 'osaka', 'spot', '유니버설 스튜디오 재팬 (USJ)', '유니버설 스튜디오 재팬 (USJ)', null, null, null, 'reviewed', '{"유니버설 스튜디오 재팬 (USJ)","해리포터 & 닌텐도 월드 어트랙션 🎢","Universal Studios Japan, Osaka"}'::text[], null, 'sapo-curated', null, null, '4.8', '해리포터 & 닌텐도 월드 어트랙션 🎢', '아시아 최고의 테마파크 중 하나입니다. 슈퍼 닌텐도 월드에 입장하려면 앱으로 정리권을 꼭 발급받거나 익스프레스 패스를 사전 구매해야 합니다.', 'Universal Studios Japan, Osaka', '08:30', '21:00', null, null, null, null, 20),
  ('osaka-003', 'osaka', 'spot', '교토 기요미즈데라 (청수사)', '교토 기요미즈데라 (청수사)', null, null, null, 'reviewed', '{"교토 기요미즈데라 (청수사)","산등성이에 세워진 목조 사찰 관람 ⛩️","Kiyomizu-dera, Kyoto"}'::text[], null, 'sapo-curated', null, null, '4.7', '산등성이에 세워진 목조 사찰 관람 ⛩️', '오사카에서 당일치기로 다녀오기 좋은 유네스코 세계유산 사찰입니다. 올라가는 언덕길(니넨자카, 산넨자카)의 고즈넉한 목조 건물들과 녹차 아이스크림이 필수 코스입니다.', 'Kiyomizu-dera, Kyoto', '06:00', '18:00', null, null, null, null, 30),
  ('osaka-004', 'osaka', 'meat', '치보 오사카 도톤보리본점', '치보 오사카 도톤보리본점', null, null, null, 'reviewed', '{"치보 오사카 도톤보리본점","치보 도톤보리 오코노미야키 (약 1,650엔)","Chibo Dotonbori, Osaka"}'::text[], null, 'sapo-curated', null, null, '4.4', '치보 도톤보리 오코노미야키 (약 1,650엔)', '철판에 즉석으로 구워주는 도톤보리 정통 오코노미야키 & 야키소바 전문점입니다. 마요네즈 쇼를 눈앞에서 볼 수 있어 눈과 입이 모두 즐겁습니다.', 'Chibo Dotonbori, Osaka', '11:00', '22:00', null, null, null, null, 40)
on conflict (id) do update set
  city_code = excluded.city_code,
  category = excluded.category,
  name = excluded.name,
  name_ko = excluded.name_ko,
  name_ja = excluded.name_ja,
  name_en = excluded.name_en,
  name_ko_auto = excluded.name_ko_auto,
  name_ko_status = excluded.name_ko_status,
  search_keywords = excluded.search_keywords,
  wikidata_id = excluded.wikidata_id,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  source_license = excluded.source_license,
  rating = excluded.rating,
  menu = excluded.menu,
  tips = excluded.tips,
  address = excluded.address,
  open_time = excluded.open_time,
  close_time = excluded.close_time,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  google_place_id = excluded.google_place_id,
  google_maps_url = excluded.google_maps_url,
  sort_order = excluded.sort_order,
  is_active = true,
  updated_at = now();

